use_frameworks!

target 'PYTreeBranchView_Example' do
  pod 'PYTreeBranchView', :path => '../'

  target 'PYTreeBranchView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
